execute @s ~ ~ ~ detect ~1 ~ ~ log2 0 structure load acacialog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log2 0 structure load acacialog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log2 0 structure load acacialog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log2 0 structure load acacialog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log2 0 structure load acacialog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log2 0 structure load acacialog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log2 0 structure load acacialog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log2 0 structure load acacialog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log2 0 structure load acacialog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log2 0 structure load acacialog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log2 0 structure load acacialog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log2 0 structure load acacialog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log2 0 structure load acacialog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log2 0 structure load acacialog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log2 0 structure load acacialog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 0 structure load acacialog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log2 0 structure load acacialog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log2 0 structure load acacialog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log2 0 structure load acacialog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log2 0 structure load acacialog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log2 0 structure load acacialog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log2 0 structure load acacialog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log2 0 structure load acacialog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 0 structure load acacialog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log2 0 structure load acacialog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log2 0 structure load acacialog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log2 4 structure load acacialog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log2 4 structure load acacialog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log2 4 structure load acacialog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log2 4 structure load acacialog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log2 4 structure load acacialog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log2 4 structure load acacialog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log2 4 structure load acacialog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log2 4 structure load acacialog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log2 4 structure load acacialog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log2 4 structure load acacialog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log2 4 structure load acacialog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log2 4 structure load acacialog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log2 4 structure load acacialog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log2 4 structure load acacialog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log2 4 structure load acacialog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 4 structure load acacialog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log2 4 structure load acacialog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log2 4 structure load acacialog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log2 4 structure load acacialog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log2 4 structure load acacialog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log2 4 structure load acacialog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log2 4 structure load acacialog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log2 4 structure load acacialog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 4 structure load acacialog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log2 4 structure load acacialog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log2 4 structure load acacialog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log2 8 structure load acacialog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log2 8 structure load acacialog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log2 8 structure load acacialog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log2 8 structure load acacialog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log2 8 structure load acacialog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log2 8 structure load acacialog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log2 8 structure load acacialog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log2 8 structure load acacialog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log2 8 structure load acacialog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log2 8 structure load acacialog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log2 8 structure load acacialog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log2 8 structure load acacialog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log2 8 structure load acacialog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log2 8 structure load acacialog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log2 8 structure load acacialog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 8 structure load acacialog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log2 8 structure load acacialog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log2 8 structure load acacialog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log2 8 structure load acacialog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log2 8 structure load acacialog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log2 8 structure load acacialog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log2 8 structure load acacialog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log2 8 structure load acacialog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 8 structure load acacialog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log2 8 structure load acacialog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log2 8 structure load acacialog ~-1 ~-1 ~1
