execute @s ~ ~ ~ detect ~1 ~ ~ crimson_stem 0 structure load crimsonstem ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ crimson_stem 0 structure load crimsonstem ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 crimson_stem 0 structure load crimsonstem ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 crimson_stem 0 structure load crimsonstem ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ crimson_stem 0 structure load crimsonstem ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ crimson_stem 0 structure load crimsonstem ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 crimson_stem 0 structure load crimsonstem ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 crimson_stem 0 structure load crimsonstem ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ crimson_stem 0 structure load crimsonstem ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ crimson_stem 0 structure load crimsonstem ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 crimson_stem 0 structure load crimsonstem ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 crimson_stem 0 structure load crimsonstem ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ crimson_stem 0 structure load crimsonstem ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ crimson_stem 0 structure load crimsonstem ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 crimson_stem 0 structure load crimsonstem ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 crimson_stem 0 structure load crimsonstem ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 crimson_stem 0 structure load crimsonstem ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 crimson_stem 0 structure load crimsonstem ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 crimson_stem 0 structure load crimsonstem ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 crimson_stem 0 structure load crimsonstem ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 crimson_stem 0 structure load crimsonstem ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 crimson_stem 0 structure load crimsonstem ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 crimson_stem 0 structure load crimsonstem ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 crimson_stem 0 structure load crimsonstem ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 crimson_stem 0 structure load crimsonstem ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 crimson_stem 0 structure load crimsonstem ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ crimson_stem 1 structure load crimsonstem ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ crimson_stem 1 structure load crimsonstem ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 crimson_stem 1 structure load crimsonstem ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 crimson_stem 1 structure load crimsonstem ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ crimson_stem 1 structure load crimsonstem ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ crimson_stem 1 structure load crimsonstem ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 crimson_stem 1 structure load crimsonstem ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 crimson_stem 1 structure load crimsonstem ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ crimson_stem 1 structure load crimsonstem ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ crimson_stem 1 structure load crimsonstem ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 crimson_stem 1 structure load crimsonstem ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 crimson_stem 1 structure load crimsonstem ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ crimson_stem 1 structure load crimsonstem ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ crimson_stem 1 structure load crimsonstem ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 crimson_stem 1 structure load crimsonstem ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 crimson_stem 1 structure load crimsonstem ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 crimson_stem 1 structure load crimsonstem ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 crimson_stem 1 structure load crimsonstem ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 crimson_stem 1 structure load crimsonstem ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 crimson_stem 1 structure load crimsonstem ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 crimson_stem 1 structure load crimsonstem ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 crimson_stem 1 structure load crimsonstem ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 crimson_stem 1 structure load crimsonstem ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 crimson_stem 1 structure load crimsonstem ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 crimson_stem 1 structure load crimsonstem ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 crimson_stem 1 structure load crimsonstem ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ crimson_stem 2 structure load crimsonstem ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ crimson_stem 2 structure load crimsonstem ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 crimson_stem 2 structure load crimsonstem ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 crimson_stem 2 structure load crimsonstem ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ crimson_stem 2 structure load crimsonstem ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ crimson_stem 2 structure load crimsonstem ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 crimson_stem 2 structure load crimsonstem ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 crimson_stem 2 structure load crimsonstem ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ crimson_stem 2 structure load crimsonstem ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ crimson_stem 2 structure load crimsonstem ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 crimson_stem 2 structure load crimsonstem ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 crimson_stem 2 structure load crimsonstem ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ crimson_stem 2 structure load crimsonstem ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ crimson_stem 2 structure load crimsonstem ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 crimson_stem 2 structure load crimsonstem ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 crimson_stem 2 structure load crimsonstem ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 crimson_stem 2 structure load crimsonstem ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 crimson_stem 2 structure load crimsonstem ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 crimson_stem 2 structure load crimsonstem ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 crimson_stem 2 structure load crimsonstem ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 crimson_stem 2 structure load crimsonstem ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 crimson_stem 2 structure load crimsonstem ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 crimson_stem 2 structure load crimsonstem ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 crimson_stem 2 structure load crimsonstem ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 crimson_stem 2 structure load crimsonstem ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 crimson_stem 2 structure load crimsonstem ~-1 ~-1 ~1
