execute @s ~ ~ ~ detect ~1 ~ ~ log 3 structure load junglelog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 3 structure load junglelog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 3 structure load junglelog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 3 structure load junglelog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 3 structure load junglelog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 3 structure load junglelog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 3 structure load junglelog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 3 structure load junglelog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 3 structure load junglelog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 3 structure load junglelog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 3 structure load junglelog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 3 structure load junglelog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 3 structure load junglelog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 3 structure load junglelog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 3 structure load junglelog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 3 structure load junglelog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 3 structure load junglelog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 3 structure load junglelog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 3 structure load junglelog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 3 structure load junglelog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 3 structure load junglelog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 3 structure load junglelog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 3 structure load junglelog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 3 structure load junglelog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 3 structure load junglelog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 3 structure load junglelog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log 7 structure load junglelog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 7 structure load junglelog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 7 structure load junglelog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 7 structure load junglelog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 7 structure load junglelog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 7 structure load junglelog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 7 structure load junglelog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 7 structure load junglelog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 7 structure load junglelog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 7 structure load junglelog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 7 structure load junglelog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 7 structure load junglelog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 7 structure load junglelog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 7 structure load junglelog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 7 structure load junglelog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 7 structure load junglelog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 7 structure load junglelog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 7 structure load junglelog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 7 structure load junglelog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 7 structure load junglelog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 7 structure load junglelog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 7 structure load junglelog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 7 structure load junglelog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 7 structure load junglelog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 7 structure load junglelog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 7 structure load junglelog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log 11 structure load junglelog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 11 structure load junglelog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 11 structure load junglelog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 11 structure load junglelog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 11 structure load junglelog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 11 structure load junglelog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 11 structure load junglelog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 11 structure load junglelog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 11 structure load junglelog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 11 structure load junglelog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 11 structure load junglelog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 11 structure load junglelog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 11 structure load junglelog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 11 structure load junglelog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 11 structure load junglelog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 11 structure load junglelog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 11 structure load junglelog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 11 structure load junglelog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 11 structure load junglelog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 11 structure load junglelog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 11 structure load junglelog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 11 structure load junglelog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 11 structure load junglelog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 11 structure load junglelog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 11 structure load junglelog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 11 structure load junglelog ~-1 ~-1 ~1
