execute @s ~ ~ ~ detect ~1 ~ ~ log 0 structure load oaklog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 0 structure load oaklog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 0 structure load oaklog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 0 structure load oaklog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 0 structure load oaklog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 0 structure load oaklog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 0 structure load oaklog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 0 structure load oaklog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 0 structure load oaklog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 0 structure load oaklog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 0 structure load oaklog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 0 structure load oaklog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 0 structure load oaklog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 0 structure load oaklog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 0 structure load oaklog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 0 structure load oaklog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 0 structure load oaklog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 0 structure load oaklog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 0 structure load oaklog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 0 structure load oaklog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 0 structure load oaklog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 0 structure load oaklog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 0 structure load oaklog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 0 structure load oaklog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 0 structure load oaklog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 0 structure load oaklog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log 4 structure load oaklog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 4 structure load oaklog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 4 structure load oaklog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 4 structure load oaklog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 4 structure load oaklog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 4 structure load oaklog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 4 structure load oaklog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 4 structure load oaklog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 4 structure load oaklog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 4 structure load oaklog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 4 structure load oaklog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 4 structure load oaklog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 4 structure load oaklog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 4 structure load oaklog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 4 structure load oaklog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 4 structure load oaklog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 4 structure load oaklog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 4 structure load oaklog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 4 structure load oaklog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 4 structure load oaklog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 4 structure load oaklog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 4 structure load oaklog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 4 structure load oaklog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 4 structure load oaklog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 4 structure load oaklog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 4 structure load oaklog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log 8 structure load oaklog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 8 structure load oaklog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 8 structure load oaklog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 8 structure load oaklog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 8 structure load oaklog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 8 structure load oaklog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 8 structure load oaklog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 8 structure load oaklog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 8 structure load oaklog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 8 structure load oaklog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 8 structure load oaklog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 8 structure load oaklog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 8 structure load oaklog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 8 structure load oaklog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 8 structure load oaklog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 8 structure load oaklog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 8 structure load oaklog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 8 structure load oaklog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 8 structure load oaklog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 8 structure load oaklog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 8 structure load oaklog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 8 structure load oaklog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 8 structure load oaklog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 8 structure load oaklog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 8 structure load oaklog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 8 structure load oaklog ~-1 ~-1 ~1
