execute @s ~ ~ ~ detect ~1 ~ ~ log 1 structure load sprucelog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 1 structure load sprucelog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 1 structure load sprucelog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 1 structure load sprucelog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 1 structure load sprucelog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 1 structure load sprucelog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 1 structure load sprucelog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 1 structure load sprucelog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 1 structure load sprucelog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 1 structure load sprucelog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 1 structure load sprucelog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 1 structure load sprucelog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 1 structure load sprucelog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 1 structure load sprucelog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 1 structure load sprucelog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 1 structure load sprucelog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 1 structure load sprucelog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 1 structure load sprucelog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 1 structure load sprucelog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 1 structure load sprucelog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 1 structure load sprucelog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 1 structure load sprucelog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 1 structure load sprucelog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 1 structure load sprucelog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 1 structure load sprucelog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 1 structure load sprucelog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log 5 structure load sprucelog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 5 structure load sprucelog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 5 structure load sprucelog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 5 structure load sprucelog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 5 structure load sprucelog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 5 structure load sprucelog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 5 structure load sprucelog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 5 structure load sprucelog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 5 structure load sprucelog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 5 structure load sprucelog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 5 structure load sprucelog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 5 structure load sprucelog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 5 structure load sprucelog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 5 structure load sprucelog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 5 structure load sprucelog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 5 structure load sprucelog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 5 structure load sprucelog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 5 structure load sprucelog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 5 structure load sprucelog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 5 structure load sprucelog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 5 structure load sprucelog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 5 structure load sprucelog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 5 structure load sprucelog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 5 structure load sprucelog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 5 structure load sprucelog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 5 structure load sprucelog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log 9 structure load sprucelog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 9 structure load sprucelog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 9 structure load sprucelog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 9 structure load sprucelog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 9 structure load sprucelog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 9 structure load sprucelog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 9 structure load sprucelog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 9 structure load sprucelog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 9 structure load sprucelog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 9 structure load sprucelog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 9 structure load sprucelog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 9 structure load sprucelog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 9 structure load sprucelog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 9 structure load sprucelog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 9 structure load sprucelog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 9 structure load sprucelog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 9 structure load sprucelog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 9 structure load sprucelog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 9 structure load sprucelog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 9 structure load sprucelog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 9 structure load sprucelog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 9 structure load sprucelog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 9 structure load sprucelog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 9 structure load sprucelog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 9 structure load sprucelog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 9 structure load sprucelog ~-1 ~-1 ~1
