execute @s ~ ~ ~ detect ~1 ~ ~ log 2 structure load birchlog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 2 structure load birchlog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 2 structure load birchlog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 2 structure load birchlog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 2 structure load birchlog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 2 structure load birchlog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 2 structure load birchlog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 2 structure load birchlog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 2 structure load birchlog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 2 structure load birchlog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 2 structure load birchlog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 2 structure load birchlog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 2 structure load birchlog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 2 structure load birchlog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 2 structure load birchlog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 2 structure load birchlog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 2 structure load birchlog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 2 structure load birchlog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 2 structure load birchlog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 2 structure load birchlog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 2 structure load birchlog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 2 structure load birchlog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 2 structure load birchlog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 2 structure load birchlog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 2 structure load birchlog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 2 structure load birchlog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log 6 structure load birchlog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 6 structure load birchlog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 6 structure load birchlog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 6 structure load birchlog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 6 structure load birchlog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 6 structure load birchlog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 6 structure load birchlog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 6 structure load birchlog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 6 structure load birchlog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 6 structure load birchlog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 6 structure load birchlog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 6 structure load birchlog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 6 structure load birchlog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 6 structure load birchlog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 6 structure load birchlog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 6 structure load birchlog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 6 structure load birchlog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 6 structure load birchlog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 6 structure load birchlog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 6 structure load birchlog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 6 structure load birchlog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 6 structure load birchlog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 6 structure load birchlog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 6 structure load birchlog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 6 structure load birchlog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 6 structure load birchlog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log 10 structure load birchlog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log 10 structure load birchlog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log 10 structure load birchlog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log 10 structure load birchlog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log 10 structure load birchlog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log 10 structure load birchlog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log 10 structure load birchlog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log 10 structure load birchlog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log 10 structure load birchlog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log 10 structure load birchlog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log 10 structure load birchlog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log 10 structure load birchlog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log 10 structure load birchlog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log 10 structure load birchlog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log 10 structure load birchlog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 10 structure load birchlog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log 10 structure load birchlog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log 10 structure load birchlog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log 10 structure load birchlog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log 10 structure load birchlog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log 10 structure load birchlog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log 10 structure load birchlog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log 10 structure load birchlog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log 10 structure load birchlog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log 10 structure load birchlog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log 10 structure load birchlog ~-1 ~-1 ~1
