execute @s ~ ~ ~ detect ~1 ~ ~ log2 1 structure load darkoaklog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log2 1 structure load darkoaklog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log2 1 structure load darkoaklog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log2 1 structure load darkoaklog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log2 1 structure load darkoaklog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log2 1 structure load darkoaklog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log2 1 structure load darkoaklog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log2 1 structure load darkoaklog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log2 1 structure load darkoaklog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log2 1 structure load darkoaklog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log2 1 structure load darkoaklog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log2 1 structure load darkoaklog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log2 1 structure load darkoaklog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log2 1 structure load darkoaklog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log2 1 structure load darkoaklog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 1 structure load darkoaklog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log2 1 structure load darkoaklog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log2 1 structure load darkoaklog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log2 1 structure load darkoaklog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log2 1 structure load darkoaklog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log2 1 structure load darkoaklog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log2 1 structure load darkoaklog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log2 1 structure load darkoaklog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 1 structure load darkoaklog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log2 1 structure load darkoaklog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log2 1 structure load darkoaklog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log2 5 structure load darkoaklog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log2 5 structure load darkoaklog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log2 5 structure load darkoaklog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log2 5 structure load darkoaklog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log2 5 structure load darkoaklog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log2 5 structure load darkoaklog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log2 5 structure load darkoaklog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log2 5 structure load darkoaklog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log2 5 structure load darkoaklog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log2 5 structure load darkoaklog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log2 5 structure load darkoaklog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log2 5 structure load darkoaklog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log2 5 structure load darkoaklog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log2 5 structure load darkoaklog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log2 5 structure load darkoaklog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 5 structure load darkoaklog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log2 5 structure load darkoaklog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log2 5 structure load darkoaklog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log2 5 structure load darkoaklog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log2 5 structure load darkoaklog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log2 5 structure load darkoaklog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log2 5 structure load darkoaklog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log2 5 structure load darkoaklog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 5 structure load darkoaklog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log2 5 structure load darkoaklog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log2 5 structure load darkoaklog ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ log2 9 structure load darkoaklog ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ log2 9 structure load darkoaklog ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 log2 9 structure load darkoaklog ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 log2 9 structure load darkoaklog ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ log2 9 structure load darkoaklog ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ log2 9 structure load darkoaklog ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 log2 9 structure load darkoaklog ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 log2 9 structure load darkoaklog ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ log2 9 structure load darkoaklog ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ log2 9 structure load darkoaklog ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 log2 9 structure load darkoaklog ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 log2 9 structure load darkoaklog ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ log2 9 structure load darkoaklog ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ log2 9 structure load darkoaklog ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 log2 9 structure load darkoaklog ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 9 structure load darkoaklog ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 log2 9 structure load darkoaklog ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 log2 9 structure load darkoaklog ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 log2 9 structure load darkoaklog ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 log2 9 structure load darkoaklog ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 log2 9 structure load darkoaklog ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 log2 9 structure load darkoaklog ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 log2 9 structure load darkoaklog ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 log2 9 structure load darkoaklog ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 log2 9 structure load darkoaklog ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 log2 9 structure load darkoaklog ~-1 ~-1 ~1
