execute @s ~ ~ ~ detect ~1 ~ ~ warped_stem 0 structure load warpedstem ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ warped_stem 0 structure load warpedstem ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 warped_stem 0 structure load warpedstem ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 warped_stem 0 structure load warpedstem ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ warped_stem 0 structure load warpedstem ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ warped_stem 0 structure load warpedstem ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 warped_stem 0 structure load warpedstem ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 warped_stem 0 structure load warpedstem ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ warped_stem 0 structure load warpedstem ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ warped_stem 0 structure load warpedstem ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 warped_stem 0 structure load warpedstem ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 warped_stem 0 structure load warpedstem ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ warped_stem 0 structure load warpedstem ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ warped_stem 0 structure load warpedstem ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 warped_stem 0 structure load warpedstem ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 warped_stem 0 structure load warpedstem ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 warped_stem 0 structure load warpedstem ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 warped_stem 0 structure load warpedstem ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 warped_stem 0 structure load warpedstem ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 warped_stem 0 structure load warpedstem ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 warped_stem 0 structure load warpedstem ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 warped_stem 0 structure load warpedstem ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 warped_stem 0 structure load warpedstem ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 warped_stem 0 structure load warpedstem ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 warped_stem 0 structure load warpedstem ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 warped_stem 0 structure load warpedstem ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ warped_stem 1 structure load warpedstem ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ warped_stem 1 structure load warpedstem ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 warped_stem 1 structure load warpedstem ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 warped_stem 1 structure load warpedstem ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ warped_stem 1 structure load warpedstem ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ warped_stem 1 structure load warpedstem ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 warped_stem 1 structure load warpedstem ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 warped_stem 1 structure load warpedstem ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ warped_stem 1 structure load warpedstem ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ warped_stem 1 structure load warpedstem ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 warped_stem 1 structure load warpedstem ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 warped_stem 1 structure load warpedstem ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ warped_stem 1 structure load warpedstem ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ warped_stem 1 structure load warpedstem ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 warped_stem 1 structure load warpedstem ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 warped_stem 1 structure load warpedstem ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 warped_stem 1 structure load warpedstem ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 warped_stem 1 structure load warpedstem ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 warped_stem 1 structure load warpedstem ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 warped_stem 1 structure load warpedstem ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 warped_stem 1 structure load warpedstem ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 warped_stem 1 structure load warpedstem ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 warped_stem 1 structure load warpedstem ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 warped_stem 1 structure load warpedstem ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 warped_stem 1 structure load warpedstem ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 warped_stem 1 structure load warpedstem ~-1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~ ~ warped_stem 2 structure load warpedstem ~1 ~ ~
execute @s ~ ~ ~ detect ~-1 ~ ~ warped_stem 2 structure load warpedstem ~-1 ~ ~
execute @s ~ ~ ~ detect ~ ~ ~1 warped_stem 2 structure load warpedstem ~ ~ ~1
execute @s ~ ~ ~ detect ~ ~ ~-1 warped_stem 2 structure load warpedstem ~ ~ ~-1
execute @s ~ ~ ~ detect ~1 ~1 ~ warped_stem 2 structure load warpedstem ~1 ~1 ~
execute @s ~ ~ ~ detect ~-1 ~1 ~ warped_stem 2 structure load warpedstem ~-1 ~1 ~
execute @s ~ ~ ~ detect ~ ~1 ~1 warped_stem 2 structure load warpedstem ~ ~1 ~1
execute @s ~ ~ ~ detect ~ ~1 ~-1 warped_stem 2 structure load warpedstem ~ ~1 ~-1
execute @s ~ ~ ~ detect ~1 ~-1 ~ warped_stem 2 structure load warpedstem ~1 ~-1 ~
execute @s ~ ~ ~ detect ~-1 ~-1 ~ warped_stem 2 structure load warpedstem ~-1 ~-1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~1 warped_stem 2 structure load warpedstem ~ ~-1 ~1
execute @s ~ ~ ~ detect ~ ~-1 ~-1 warped_stem 2 structure load warpedstem ~ ~-1 ~-1
execute @s ~ ~ ~ detect ~ ~1 ~ warped_stem 2 structure load warpedstem ~ ~1 ~
execute @s ~ ~ ~ detect ~ ~-1 ~ warped_stem 2 structure load warpedstem ~ ~-1 ~
execute @s ~ ~ ~ detect ~1 ~ ~1 warped_stem 2 structure load warpedstem ~1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 warped_stem 2 structure load warpedstem ~1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~-1 warped_stem 2 structure load warpedstem ~-1 ~ ~-1
execute @s ~ ~ ~ detect ~-1 ~ ~1 warped_stem 2 structure load warpedstem ~-1 ~ ~1
execute @s ~ ~ ~ detect ~1 ~1 ~1 warped_stem 2 structure load warpedstem ~1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~1 ~-1 warped_stem 2 structure load warpedstem ~1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~-1 warped_stem 2 structure load warpedstem ~-1 ~1 ~-1
execute @s ~ ~ ~ detect ~-1 ~1 ~1 warped_stem 2 structure load warpedstem ~-1 ~1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~1 warped_stem 2 structure load warpedstem ~1 ~-1 ~1
execute @s ~ ~ ~ detect ~1 ~-1 ~-1 warped_stem 2 structure load warpedstem ~1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 warped_stem 2 structure load warpedstem ~-1 ~-1 ~-1
execute @s ~ ~ ~ detect ~-1 ~-1 ~1 warped_stem 2 structure load warpedstem ~-1 ~-1 ~1
